# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_ultrafast <- function(nedge, L, E, pic_ace, ace_hat, var_hat, len_vec, pic_len_vec) {
    .Call(`_phylocurve_C_ultrafast`, nedge, L, E, pic_ace, ace_hat, var_hat, len_vec, pic_len_vec)
}

multipic <- function(ntip, nnode, edge1, edge2, edge_len, phe, contr, var_contr, scaled, pic_len, pic_recon) {
    .Call(`_phylocurve_multipic`, ntip, nnode, edge1, edge2, edge_len, phe, contr, var_contr, scaled, pic_len, pic_recon)
}

multipic2 <- function(ntip, nnode, edge1, edge2, edge_len, phe, contr, var_contr, scaled, pic_len, pic_recon) {
    .Call(`_phylocurve_multipic2`, ntip, nnode, edge1, edge2, edge_len, phe, contr, var_contr, scaled, pic_len, pic_recon)
}

logdet <- function(A) {
    .Call(`_phylocurve_logdet`, A)
}

Rinv4 <- function(nspecies, nedge, ngroups, ind, len_vec, anc, des, R, painted_edges, phylocovs, REML) {
    .Call(`_phylocurve_Rinv4`, nspecies, nedge, ngroups, ind, len_vec, anc, des, R, painted_edges, phylocovs, REML)
}

Rinv6 <- function(nspecies, nedge, ngroups, ind, len_vec, anc, des, L, R, painted_edges, phylocovs, REML) {
    .Call(`_phylocurve_Rinv6`, nspecies, nedge, ngroups, ind, len_vec, anc, des, L, R, painted_edges, phylocovs, REML)
}

theta_Rinv6 <- function(nspecies, nedge, ngroups, ind, len_vec, anc, des, L, R, painted_edges, phylocovs, REML) {
    .Call(`_phylocurve_theta_Rinv6`, nspecies, nedge, ngroups, ind, len_vec, anc, des, L, R, painted_edges, phylocovs, REML)
}

fast_transform <- function(m) {
    .Call(`_phylocurve_fast_transform`, m)
}

